package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/rishimantri795/CLICreator/runtime/httpclient"
	"github.com/rishimantri795/CLICreator/runtime/output"
	"github.com/spf13/cobra"
)

var conversationsSendAutomatedMessageCmd = &cobra.Command{
	Use:   "send-automated-message",
	Short: "Send an automated message to a visitor",
	RunE:  runConversationsSendAutomatedMessage,
}

var conversationsSendAutomatedMessageFlags struct {
	visitorId string
	text      string
	agentId   string
	groupId   string
	body      string
}

func init() {
	conversationsSendAutomatedMessageCmd.Flags().StringVar(&conversationsSendAutomatedMessageFlags.visitorId, "visitor-id", "", "visitor’s ID received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a> or generated by you to <a href=\"https://developers.brevo.com/docs/customize-the-widget#identifying-existing-users\">bind existing user account to Conversations</a>")
	// Note: body fields are not MarkFlagRequired — --body JSON satisfies them too.
	conversationsSendAutomatedMessageCmd.Flags().StringVar(&conversationsSendAutomatedMessageFlags.text, "text", "", "message text")
	// Note: body fields are not MarkFlagRequired — --body JSON satisfies them too.
	conversationsSendAutomatedMessageCmd.Flags().StringVar(&conversationsSendAutomatedMessageFlags.agentId, "agent-id", "", "agent ID. It can be found on agent’s page or received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a>.")
	// Note: body fields are not MarkFlagRequired — --body JSON satisfies them too.
	conversationsSendAutomatedMessageCmd.Flags().StringVar(&conversationsSendAutomatedMessageFlags.groupId, "group-id", "", "group ID. It can be found on group’s page.")
	// Note: body fields are not MarkFlagRequired — --body JSON satisfies them too.
	conversationsSendAutomatedMessageCmd.Flags().StringVar(&conversationsSendAutomatedMessageFlags.body, "body", "", "Full request body as JSON (overrides individual flags)")

	conversationsCmd.AddCommand(conversationsSendAutomatedMessageCmd)
}

func runConversationsSendAutomatedMessage(cmd *cobra.Command, args []string) error {
	// --schema: print full input/output type contract without making any network call.
	if rootFlags.schema {
		type flagSchema struct {
			Name        string `json:"name"`
			Type        string `json:"type"`
			Required    bool   `json:"required"`
			Location    string `json:"location"`
			Description string `json:"description,omitempty"`
		}
		var flags []flagSchema
		flags = append(flags, flagSchema{
			Name:        "visitor-id",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "visitor’s ID received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a> or generated by you to <a href=\"https://developers.brevo.com/docs/customize-the-widget#identifying-existing-users\">bind existing user account to Conversations</a>",
		})
		flags = append(flags, flagSchema{
			Name:        "text",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "message text",
		})
		flags = append(flags, flagSchema{
			Name:        "agent-id",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "agent ID. It can be found on agent’s page or received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a>.",
		})
		flags = append(flags, flagSchema{
			Name:        "group-id",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "group ID. It can be found on group’s page.",
		})

		type responseSchema struct {
			Status      string `json:"status"`
			ContentType string `json:"content_type,omitempty"`
			Description string `json:"description,omitempty"`
		}
		var responses []responseSchema
		responses = append(responses, responseSchema{
			Status:      "200",
			ContentType: "application/json",
			Description: "Newly created message is returned as a response",
		})
		responses = append(responses, responseSchema{
			Status:      "400",
			ContentType: "application/json",
			Description: "Returned when invalid data posted",
		})

		schema := map[string]any{
			"command":     "send-automated-message",
			"description": "Send an automated message to a visitor",
			"http": map[string]any{
				"method": "POST",
				"path":   "/conversations/pushedMessages",
			},
			"input": map[string]any{
				"flags":         flags,
				"body_flag":     true,
				"body_required": true,
			},
			"output": map[string]any{
				"responses": responses,
			},
			"semantics": map[string]any{
				"safe":         false,
				"idempotent":   false,
				"reversible":   true,
				"side_effects": []string{"sends_notification"},
				"impact":       "high",
			},
			"requires_auth": true,
		}
		data, _ := json.MarshalIndent(schema, "", "  ")
		fmt.Fprintln(_stdoutCounter, string(data))
		return nil
	}

	cfg, err := rootConfig()
	if err != nil {
		e := output.NetworkError(err)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	client := httpclient.New(cfg.BaseURL, cfg.AuthProvider())
	client.Debug = rootFlags.debug
	client.DryRun = rootFlags.dryRun
	if rootFlags.noRetries {
		client.RetryConfig.MaxRetries = 0
	}

	// Build path params
	pathParams := map[string]string{}

	req := &httpclient.Request{
		Method:      "POST",
		Path:        httpclient.SubstitutePath("/conversations/pushedMessages", pathParams),
		QueryParams: map[string]string{},
		ArrayParams: map[string][]string{},
		Headers:     map[string]string{},
	}

	// Query parameters

	// Header parameters

	// Request body
	bodyMap := map[string]any{}
	if conversationsSendAutomatedMessageFlags.body != "" {
		if err := json.Unmarshal([]byte(conversationsSendAutomatedMessageFlags.body), &bodyMap); err != nil {
			_invState.errorType = "parse_error"
			cliErr := &output.CLIError{
				Error:    true,
				Code:     "validation_error",
				Message:  fmt.Sprintf("invalid JSON in --body: %v", err),
				ExitCode: output.ExitValidation,
			}
			cliErr.Write(os.Stderr)
			return output.NewExitError(cliErr)
		}
	}
	// Individual flags overlay onto body (flags take precedence over --body JSON)
	if cmd.Flags().Changed("visitor-id") {
		bodyMap["visitorId"] = conversationsSendAutomatedMessageFlags.visitorId
	}
	if cmd.Flags().Changed("text") {
		bodyMap["text"] = conversationsSendAutomatedMessageFlags.text
	}
	if cmd.Flags().Changed("agent-id") {
		bodyMap["agentId"] = conversationsSendAutomatedMessageFlags.agentId
	}
	if cmd.Flags().Changed("group-id") {
		bodyMap["groupId"] = conversationsSendAutomatedMessageFlags.groupId
	}
	req.Body = bodyMap

	resp, err := client.Do(req)
	if err != nil {
		if strings.Contains(err.Error(), "timeout") || strings.Contains(err.Error(), "deadline exceeded") {
			_invState.errorType = "timeout"
		} else {
			_invState.errorType = "network_error"
		}
		e := output.NetworkError(err)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	if resp.StatusCode >= 400 {
		if resp.StatusCode >= 500 {
			_invState.errorType = "http_5xx"
		} else {
			_invState.errorType = "http_4xx"
		}
		_invState.errorCode = resp.StatusCode
		e := output.HTTPError(resp.StatusCode, resp.Body)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	if rootFlags.jq != "" {
		return output.JQFilter(_stdoutCounter, resp.Body, rootFlags.jq)
	}
	return output.Print(_stdoutCounter, resp.Body, output.Format(cfg.OutputFormat))
}
