package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/rishimantri795/CLICreator/runtime/httpclient"
	"github.com/rishimantri795/CLICreator/runtime/output"
	"github.com/spf13/cobra"
)

var conversationsSendMessageAsAgentCmd = &cobra.Command{
	Use:   "send-message-as-agent",
	Short: "Send a message as an agent",
	RunE:  runConversationsSendMessageAsAgent,
}

var conversationsSendMessageAsAgentFlags struct {
	visitorId    string
	text         string
	agentId      string
	receivedFrom string
	agentEmail   string
	agentName    string
	body         string
}

func init() {
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.visitorId, "visitor-id", "", "visitor’s ID received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a> or generated by you to <a href=\"https://developers.brevo.com/docs/customize-the-widget#identifying-existing-users\">bind existing user account to Conversations</a>")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.text, "text", "", "message text")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.agentId, "agent-id", "", "agent ID. It can be found on agent’s page or received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a>. Alternatively, you can use `agentEmail` + `agentName` + `receivedFrom` instead (all 3 fields required).")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.receivedFrom, "received-from", "", "mark your messages to distinguish messages created by you from the others.")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.agentEmail, "agent-email", "", "agent email. When sending messages from a standalone system, it’s hard to maintain a 1-to-1 relationship between the users of both systems. In this case, an agent can be specified by their email address.")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.agentName, "agent-name", "", "agent name")
	// Note: body fields are not MarkFlagRequired in JSON mode — --body satisfies them too.
	conversationsSendMessageAsAgentCmd.Flags().StringVar(&conversationsSendMessageAsAgentFlags.body, "body", "", "Full request body as JSON. Individual body flags override matching keys in this JSON.")

	conversationsCmd.AddCommand(conversationsSendMessageAsAgentCmd)
}

func runConversationsSendMessageAsAgent(cmd *cobra.Command, args []string) error {
	// --schema: print full input/output type contract without making any network call.
	if rootFlags.schema {
		type flagSchema struct {
			Name        string `json:"name"`
			Type        string `json:"type"`
			Required    bool   `json:"required"`
			Location    string `json:"location"`
			Description string `json:"description,omitempty"`
		}
		var flags []flagSchema
		flags = append(flags, flagSchema{
			Name:        "visitor-id",
			Type:        "string",
			Required:    true,
			Location:    "body",
			Description: "visitor’s ID received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a> or generated by you to <a href=\"https://developers.brevo.com/docs/customize-the-widget#identifying-existing-users\">bind existing user account to Conversations</a>",
		})
		flags = append(flags, flagSchema{
			Name:        "text",
			Type:        "string",
			Required:    true,
			Location:    "body",
			Description: "message text",
		})
		flags = append(flags, flagSchema{
			Name:        "agent-id",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "agent ID. It can be found on agent’s page or received <a href=\"https://developers.brevo.com/docs/conversations-webhooks\">from a webhook</a>. Alternatively, you can use `agentEmail` + `agentName` + `receivedFrom` instead (all 3 fields required).",
		})
		flags = append(flags, flagSchema{
			Name:        "received-from",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "mark your messages to distinguish messages created by you from the others.",
		})
		flags = append(flags, flagSchema{
			Name:        "agent-email",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "agent email. When sending messages from a standalone system, it’s hard to maintain a 1-to-1 relationship between the users of both systems. In this case, an agent can be specified by their email address.",
		})
		flags = append(flags, flagSchema{
			Name:        "agent-name",
			Type:        "string",
			Required:    false,
			Location:    "body",
			Description: "agent name",
		})

		type responseSchema struct {
			Status      string `json:"status"`
			ContentType string `json:"content_type,omitempty"`
			Description string `json:"description,omitempty"`
		}
		var responses []responseSchema
		responses = append(responses, responseSchema{
			Status:      "200",
			ContentType: "application/json",
			Description: "Newly created message is returned as a response",
		})
		responses = append(responses, responseSchema{
			Status:      "400",
			ContentType: "application/json",
			Description: "Returned when invalid data posted",
		})

		schema := map[string]any{
			"command":     "send-message-as-agent",
			"description": "Send a message as an agent",
			"http": map[string]any{
				"method": "POST",
				"path":   "/conversations/messages",
			},
			"input": map[string]any{
				"flags":         flags,
				"body_flag":     true,
				"body_required": true,
			},
			"output": map[string]any{
				"responses": responses,
			},
			"semantics": map[string]any{
				"safe":         false,
				"idempotent":   false,
				"reversible":   true,
				"side_effects": []string{"sends_notification"},
				"impact":       "high",
			},
			"requires_auth": true,
		}
		data, _ := json.MarshalIndent(schema, "", "  ")
		fmt.Fprintln(_stdoutCounter, string(data))
		return nil
	}

	cfg, err := rootConfig()
	if err != nil {
		e := output.NetworkError(err)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	client := httpclient.New(cfg.BaseURL, cfg.AuthProvider())
	client.Debug = rootFlags.debug
	client.DryRun = rootFlags.dryRun
	if rootFlags.noRetries {
		client.RetryConfig.MaxRetries = 0
	}

	// Build path params
	pathParams := map[string]string{}

	req := &httpclient.Request{
		Method:      "POST",
		Path:        httpclient.SubstitutePath("/conversations/messages", pathParams),
		QueryParams: map[string]string{},
		ArrayParams: map[string][]string{},
		Headers:     map[string]string{},
	}

	// Query parameters

	// Header parameters

	// Request body
	bodyMap := map[string]any{}
	if conversationsSendMessageAsAgentFlags.body != "" {
		if err := json.Unmarshal([]byte(conversationsSendMessageAsAgentFlags.body), &bodyMap); err != nil {
			_invState.errorType = "parse_error"
			cliErr := &output.CLIError{
				Error:    true,
				Code:     "validation_error",
				Message:  fmt.Sprintf("invalid JSON in --body: %v", err),
				ExitCode: output.ExitValidation,
			}
			cliErr.Write(os.Stderr)
			return output.NewExitError(cliErr)
		}
	}
	// Individual flags overlay onto body (flags take precedence over --body JSON)
	if cmd.Flags().Changed("visitor-id") {
		bodyMap["visitorId"] = conversationsSendMessageAsAgentFlags.visitorId
	}
	if cmd.Flags().Changed("text") {
		bodyMap["text"] = conversationsSendMessageAsAgentFlags.text
	}
	if cmd.Flags().Changed("agent-id") {
		bodyMap["agentId"] = conversationsSendMessageAsAgentFlags.agentId
	}
	if cmd.Flags().Changed("received-from") {
		bodyMap["receivedFrom"] = conversationsSendMessageAsAgentFlags.receivedFrom
	}
	if cmd.Flags().Changed("agent-email") {
		bodyMap["agentEmail"] = conversationsSendMessageAsAgentFlags.agentEmail
	}
	if cmd.Flags().Changed("agent-name") {
		bodyMap["agentName"] = conversationsSendMessageAsAgentFlags.agentName
	}
	req.Body = bodyMap

	resp, err := client.Do(req)
	if err != nil {
		if strings.Contains(err.Error(), "timeout") || strings.Contains(err.Error(), "deadline exceeded") {
			_invState.errorType = "timeout"
		} else {
			_invState.errorType = "network_error"
		}
		e := output.NetworkError(err)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	if resp.StatusCode >= 400 {
		if resp.StatusCode >= 500 {
			_invState.errorType = "http_5xx"
		} else {
			_invState.errorType = "http_4xx"
		}
		_invState.errorCode = resp.StatusCode
		e := output.HTTPError(resp.StatusCode, resp.Body)
		e.Write(os.Stderr)
		return output.NewExitError(e)
	}

	if rootFlags.jq != "" {
		return output.JQFilter(_stdoutCounter, resp.Body, rootFlags.jq)
	}
	return output.Print(_stdoutCounter, resp.Body, output.Format(cfg.OutputFormat))
}
